version: "3"
networks:
  microservice-network:
    driver: bridge

services:
  db:
    image: mongo:latest
    hostname: db
    ports:
      - 27012:27012
    command: mongod --port 27012
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dionis
      - MONGO_INITDB_ROOT_PASSWORD=dionis98
    restart: always
    networks:
      - microservice-network

  project:
    image: projectimage:latest
    depends_on:
      - db
    environment:
      - spring.data.mongodb.port=27012
      - spring.data.mongodb.host=db
      - spring.data.mongodb.username=dionis
      - spring.data.mongodb.password=dionis98
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.database=projectdb
      - spring.data.mongodb.auto-index-creation=true
      - server.port=8981
      - spring.application.name= project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8981:8981
    restart: always
    networks:
      - microservice-network